kind: pipeline
type: docker
name: main-page

clone:
  git:
    environment:
      HTTP_PROXY: http://172.18.0.3:7890 
      HTTPS_PROXY: http://172.18.0.3:7890

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm config set proxy http://172.18.0.3:7890
      - npm config set https-proxy http://172.18.0.3:7890
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    volumes:
      - name: site_data
        path: /opt/1panel/1panel/www/sites
    commands:
      - mkdir -p /opt/1panel/1panel/www/sites/zhoujump.club/index
      - cp -r ./dist/* /opt/1panel/1panel/www/sites/zhoujump.club/index/

volumes:
  - name: site_data
    host:
      path: /opt/1panel/1panel/www/sites
