kind: pipeline
type: docker
name: main-page

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    volumes:
      - name: site_data
        path: /opt/1panel/1panel/www/sites
    commands:
      - mkdir -p /opt/1panel/1panel/www/sites/zhoujump.club/index
      - cp -r ./dist/* /opt/1panel/1panel/www/sites/zhoujump.club/index/

volumes:
  - name: site_data
    host:
      path: /opt/1panel/1panel/www/sites
