kind: pipeline
type: docker
name: main-page

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    commands:
      - echo "Checking current directory..."
      - pwd
      - echo "Checking dist directory contents..."
      - ls -la ./dist
      - echo "Checking target directory..."
      - ls -la /opt/1panel/sites/
      - mkdir -p /opt/1panel/sites/zhoujump.club/index
      - echo "Copying files..."
      - cp -r ./dist/* /opt/1panel/sites/zhoujump.club/index/
      - echo "Checking copied files..."
      - ls -la /opt/1panel/sites/zhoujump.club/index/
