kind: pipeline
type: docker
name: main-page

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git config --global http.proxy http://127.0.0.1:7890
      - git config --global https.proxy http://127.0.0.1:7890
      - git clone https://github.com/zhoujump/main-page.git .
      - git checkout version2

  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    volumes:
      - name: site_data
        path: /opt/1panel/1panel/www/sites
    commands:
      - mkdir -p /opt/1panel/1panel/www/sites/zhoujump.club/index
      - cp -r ./dist/* /opt/1panel/1panel/www/sites/zhoujump.club/index/

volumes:
  - name: site_data
    host:
      path: /opt/1panel/1panel/www/sites
