kind: pipeline
type: docker
name: main-page

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    commands:
      - mkdir -p /opt/1panel/sites/zhoujump.club/index
      - cp -r ./dist/* /opt/1panel/sites/zhoujump.club/index/
