kind: pipeline
type: docker
name: main-page

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run docs:build

  - name: deploy
    image: busybox
    volumes:
      - name: site_data
        path: /opt/1panel/sites
    commands:
      - echo "Starting deployment process..."
      - echo "Checking current directory..."
      - pwd
      - echo "Checking if dist directory exists and its contents..."
      - ls -la ./dist
      - echo "Checking if volumes are correctly mounted..."
      - ls -la /opt/1panel/
      - ls -la /opt/1panel/sites/
      - echo "Checking current user..."
      - id
      - echo "Creating target directory..."
      - mkdir -p /opt/1panel/sites/zhoujump.club/index
      - echo "Setting permissions on target directory..."
      - chmod -R 777 /opt/1panel/sites/zhoujump.club
      - echo "Copying files with verbose output..."
      - cp -rv ./dist/* /opt/1panel/sites/zhoujump.club/index/
      - echo "Verifying copy operation..."
      - ls -la /opt/1panel/sites/zhoujump.club/index/
      - echo "Checking file content..."
      - cat /opt/1panel/sites/zhoujump.club/index/index.html | head -10
      - echo "Deployment completed!"

volumes:
  - name: site_data
    host:
      path: /opt/1panel/sites
